version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"  # Backend API
      - "5173:5173"  # Vite dev server
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGO_URI=mongodb+srv://samayantarajghimire:Momlopme1@cluster0.v1pzu.mongodb.net/mern-ecommerce?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=Krew8JDTezk83Qup9lQyxG1QFCoel11owvl9nDReRBA=
      - ALLOWED_ORIGINS=http://localhost:5173
      - UPSTASH_REDIS_REST_URL=https://certain-polecat-11092.upstash.io
      - UPSTASH_REDIS_REST_TOKEN=AStUAAIjcDE5NmIwMTg3MWQzYzY0MDc4OTNiZjEyYzEyMmY4MTdjOXAxMA
      - KHALTI_SECRET_KEY=39de3bb7168c488aa30f9a52cc8e3e72
      - CLOUDINARY_CLOUD_NAME=djm3vrupr
      - CLOUDINARY_API_KEY=449793278643861
      - CLOUDINARY_API_SECRET=ZLPMSy6jDqdr6skHWJEhPnSxzBE
      - VITE_API_URL=http://localhost:5001
      - VITE_KHALTI_PUBLIC_KEY=69ed8109689f46a4b0fa823381aaff7c
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - /app/server/node_modules
      - /app/client/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
